# Generated by Django 4.0.6 on 2022-08-09 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='JiraTransition',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transition_alias', models.CharField(default='', max_length=64)),
                ('transition_name', models.CharField(max_length=64)),
                ('garrett_action', models.CharField(choices=[('CREATE_REVIEW', 'Create Review'), ('COMPLETE_REVIEW', 'Complete Review'), ('CREATE_THREAT_MODEL', 'Create Threat Model'), ('COMPLETE_THREAT_MODEL', 'Complete Threat Model'), ('CREATE_TEST', 'Create Test'), ('COMPLETE_TEST', 'Complete Test')], max_length=21, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readable_id', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('owasp_level', models.IntegerField(default=0)),
                ('owasp_section', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(default=None, null=True)),
                ('jira_issue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jiraissue')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityTest',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(default=None, null=True)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.review')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('SIGNED_OFF', 'Signed Off'), ('NOTIFICATION', 'Notification'), ('THREAT MODEL', 'Threat Model'), ('TESTING', 'Testing')], default='SIGNED_OFF', max_length=20)),
                ('confluence_parent_id', models.IntegerField(null=True)),
                ('confluence_space', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatModel',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(default=None, null=True)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.review')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FAIL', 'Fail'), ('SUCCESS', 'Success')], default='PENDING', max_length=10)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirement')),
                ('security_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.securitytest')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('requirements', models.ManyToManyField(blank=True, to='api.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='securitytest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
        migrations.AddField(
            model_name='securitytest',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.template'),
        ),
        migrations.AddField(
            model_name='review',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.service'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='services',
            field=models.ManyToManyField(related_name='jira_issues', to='api.service'),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('impact', models.CharField(choices=[('INFORMATIONAL', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFORMATIONAL', max_length=13)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FIXED', 'Fixed')], default='PENDING', max_length=7)),
                ('security_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.securitytest')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.testcase')),
            ],
        ),
    ]
