# Generated by Django 4.0.1 on 2022-02-17 22:07

import json

from django.db import migrations


def add_initial_requirements(apps, schema_editor):
    Requirement = apps.get_model('api', 'Requirement')

    requirement_data = []
    with open('api/fixtures/initial_owasp_requirements.json') as fd:
        requirement_data = json.load(fd)

    for item in requirement_data:
        req_data = item['fields']
        r = Requirement(readable_id=req_data['readable_id'],
                        owasp_level=req_data['owasp_level'],
                        owasp_section=req_data['owasp_section'],
                        description=req_data['description'])
        r.save()


def add_initial_templates(apps, schema_editor):
    Template = apps.get_model('api', 'template')
    Requirement = apps.get_model('api', 'Requirement')

    for i in range(1, 4):
        name = f'Default template - OWASP Level {i}'
        reqs = Requirement.objects.filter(owasp_level__lte=i)
        t = Template(name=name)
        t.save()
        t.requirements.set(reqs)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_requirements),
        migrations.RunPython(add_initial_templates)
    ]
