# Generated by Django 4.0.6 on 2022-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_owasp_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatmodel',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
