# Generated by Django 4.0.6 on 2022-08-03 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_owasp_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraTransition',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transition_alias', models.CharField(default='', max_length=64)),
                ('transition_name', models.CharField(max_length=64)),
                ('garrett_action', models.CharField(choices=[('CREATE_TEST', 'Create Test'), ('COMPLETE_TEST', 'Complete Test')], max_length=13, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=64)),
                ('services', models.ManyToManyField(related_name='jira_issues', to='api.service')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='jira_issue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jiraissue'),
        ),
    ]
