# Generated by Django 4.0.6 on 2022-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_threatmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='threatmodel',
            name='service',
        ),
        migrations.AddField(
            model_name='securitytest',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.service'),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.service'),
        ),
        migrations.AlterField(
            model_name='securitytest',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
