# Generated by Django 4.0.6 on 2022-08-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_securitytest_service_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('confluence_parent_id', 'confluence_space')},
        ),
    ]
