# Generated by Django 4.1.3 on 2022-12-01 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_transition_name_jiratransition_transition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatmodel',
            name='boundaries_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='business_logic_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TMParticipant',
            fields=[
                ('oid',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('threat_model',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='participants',
                                   to='api.threatmodel')),
            ],
        ),
    ]
